Repository selectel/terraform-provider-selectel, pull requests merged in 2019-09, with the labels that each got.

#66 Resell V2: implement support of revoke token
  go.mod
  go.sum
  selectel/resource_selectel_vpc_token_v2.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/doc.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/tokens/requests.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/users/doc.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/users/requests.go
  vendor/modules.txt
Labels: dependencies, size/M

#65 Resell V2: implement support of user import
  go.mod
  selectel/import_selectel_vpc_user_v2_test.go
  selectel/resource_selectel_vpc_user_v2.go
  selectel/resource_selectel_vpc_user_v2_test.go
Labels: dependencies, size/M

#67 VPC: remove crossregion_subnet_v2 resource
  go.mod
  go.sum
  selectel/import_selectel_vpc_crossregion_subnet_v2_test.go
  selectel/provider.go
  selectel/regions.go
  selectel/regions_test.go
  selectel/resource_selectel_vpc_crossregion_subnet_v2.go
  selectel/resource_selectel_vpc_crossregion_subnet_v2_test.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/doc.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/requests.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/requests_opts.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/schemas.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
  vendor/modules.txt
  website/docs/r/vpc_crossregion_subnet_v2.html.markdown
  website/selectel.erb
Labels: dependencies, documentation, size/XL

#68 CI: use v1.19.1 release of GolangCI
  .gitignore
  .golangci.yml
  .travis.yml
Labels: size/XS

#69 Properly deprecate the vpc_crossregion_subnet_v2
  CHANGELOG.md
  selectel/errors.go
  selectel/errors_test.go
  selectel/provider.go
  selectel/regions.go
  selectel/resource_selectel_vpc_crossregion_subnet_v2.go
  website/docs/r/vpc_crossregion_subnet_v2.html.markdown
Labels: documentation, size/L

#70 VPC V2 API: fix User importing
  selectel/import_selectel_vpc_user_v2_test.go
  selectel/resource_selectel_vpc_user_v2.go
Labels: size/XS

#73 Fix 404 error checks
  go.mod
  go.sum
  selectel/resource_selectel_vpc_floatingip_v2.go
  selectel/resource_selectel_vpc_keypair_v2.go
  selectel/resource_selectel_vpc_license_v2.go
  selectel/resource_selectel_vpc_project_v2.go
  selectel/resource_selectel_vpc_role_v2.go
  selectel/resource_selectel_vpc_subnet_v2.go
  selectel/resource_selectel_vpc_token_v2.go
  selectel/resource_selectel_vpc_user_v2.go
  selectel/resource_selectel_vpc_vrrp_subnet_v2.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
  vendor/modules.txt
Labels: dependencies, size/L
