Repository selectel/terraform-provider-selectel, pull requests merged in 2019-01, with the labels that each got.

#33 Resellv2/keypair resource
  Gopkg.lock
  selvpc/errors.go
  selvpc/import_selvpc_resell_keypair_v2_test.go
  selvpc/provider.go
  selvpc/regions.go
  selvpc/regions_test.go
  selvpc/resource_selvpc_resell_keypair_v2.go
  selvpc/resource_selvpc_resell_keypair_v2_test.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/keypairs/doc.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/keypairs/requests.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/keypairs/requests_opts.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/keypairs/schemas.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/doc.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/roles/requests.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
  website/docs/r/resell_keypair_v2.html.markdown
  website/selvpc.erb
Labels: dependencies, documentation, size/XL

#34 Refactor: unify debug messages
  selvpc/errors.go
  selvpc/errors_test.go
  selvpc/messages.go
  selvpc/messages_test.go
  selvpc/provider.go
  selvpc/resource_selvpc_resell_floatingip_v2.go
  selvpc/resource_selvpc_resell_keypair_v2.go
  selvpc/resource_selvpc_resell_license_v2.go
  selvpc/resource_selvpc_resell_project_v2.go
  selvpc/resource_selvpc_resell_role_v2.go
  selvpc/resource_selvpc_resell_subnet_v2.go
  selvpc/resource_selvpc_resell_token_v2.go
  selvpc/resource_selvpc_resell_user_v2.go
Labels: size/L

#36 Subnet: remove "type" argument from docs
  website/docs/r/resell_subnet_v2.html.markdown
Labels: documentation, size/XS

#37 CI: use GolangCI-Lint v1.12.5
  .travis.yml
Labels: size/XS

#39 Refactoring: remove redundant checks in servers.go
  selvpc/servers.go
Labels: size/XS

#40 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
Labels: size/XS

#42 Resell V2 Token - fix acceptance test
  selvpc/resource_selvpc_resell_token_v2_test.go
Labels: size/XS

#43 ResellV2: add Cross-region subnet resource
  Gopkg.lock
  selvpc/errors.go
  selvpc/errors_test.go
  selvpc/import_selvpc_resell_crossregion_subnet_v2_test.go
  selvpc/networking.go
  selvpc/networking_test.go
  selvpc/provider.go
  selvpc/regions.go
  selvpc/regions_test.go
  selvpc/resource_selvpc_resell_crossregion_subnet_v2.go
  selvpc/resource_selvpc_resell_crossregion_subnet_v2_test.go
  selvpc/resource_selvpc_resell_vrrp_subnet_v2.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/doc.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/requests.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/requests_opts.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/crossregionsubnets/schemas.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/resell/v2/subnets/schemas.go
  vendor/github.com/selectel/go-selvpcclient/selvpcclient/selvpc.go
  website/docs/r/resell_crossregion_subnet_v2.html.markdown
  website/selvpc.erb
Labels: dependencies, documentation, size/XL

#46 Resell V2 Cross-region subnets: use lower-case
  selvpc/provider.go
  selvpc/resource_selvpc_resell_crossregion_subnet_v2_test.go
Labels: size/XS
