Repository selectel/terraform-provider-selectel, pull requests merged in 2020-05, with the labels that each got.

#85 MKS V1: add kube version suppress diff func
  selectel/mks.go
  selectel/mks_test.go
  selectel/resource_selectel_mks_cluster_v1.go
Labels: size/L

#86 Domains V1: add domain resource
  go.mod
  go.sum
  selectel/config.go
  selectel/errors.go
  selectel/errors_test.go
  selectel/import_selectel_domains_domain_v1_test.go
  selectel/provider.go
  selectel/resource_selectel_domains_domain_v1.go
  selectel/resource_selectel_domains_domain_v1_test.go
  vendor/github.com/selectel/domains-go/LICENSE
  vendor/github.com/selectel/domains-go/pkg/v1/client.go
  vendor/github.com/selectel/domains-go/pkg/v1/doc.go
  vendor/github.com/selectel/domains-go/pkg/v1/domain/doc.go
  vendor/github.com/selectel/domains-go/pkg/v1/domain/requests.go
  vendor/github.com/selectel/domains-go/pkg/v1/domain/requests_opts.go
  vendor/github.com/selectel/domains-go/pkg/v1/domain/schemas.go
  vendor/modules.txt
  website/docs/r/domains_domain_v1.html.markdown
  website/selectel.erb
Labels: dependencies, documentation, size/XL

#88 MKS Nodegroup V1: add labels support
  go.mod
  go.sum
  selectel/mks.go
  selectel/mks_test.go
  selectel/resource_selectel_mks_nodegroup_v1.go
  selectel/resource_selectel_mks_nodegroup_v1_test.go
  vendor/github.com/selectel/mks-go/pkg/v1/client.go
  vendor/github.com/selectel/mks-go/pkg/v1/cluster/doc.go
  vendor/github.com/selectel/mks-go/pkg/v1/cluster/schemas.go
  vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/doc.go
  vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/requests.go
  vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/requests_opts.go
  vendor/github.com/selectel/mks-go/pkg/v1/nodegroup/schemas.go
  vendor/modules.txt
  website/docs/r/mks_nodegroup_v1.html.markdown
Labels: dependencies, documentation, size/L

#90 MKS Nodegroup V1: fix resource import
  selectel/import_selectel_mks_nodegroup_v1_test.go
  selectel/resource_selectel_mks_nodegroup_v1.go
Labels: size/XS

#91 Domains V1: add record resource
  go.sum
  selectel/domains.go
  selectel/domains_test.go
  selectel/errors.go
  selectel/errors_test.go
  selectel/import_selectel_domains_record_v1_test.go
  selectel/provider.go
  selectel/resource_selectel_domains_record_v1.go
  selectel/resource_selectel_domains_record_v1_test.go
  vendor/github.com/selectel/domains-go/pkg/v1/record/doc.go
  vendor/github.com/selectel/domains-go/pkg/v1/record/requests.go
  vendor/github.com/selectel/domains-go/pkg/v1/record/requests_opts.go
  vendor/github.com/selectel/domains-go/pkg/v1/record/schemas.go
  vendor/modules.txt
  website/docs/r/domains_record_v1.html.markdown
  website/selectel.erb
Labels: dependencies, documentation, size/XXL

#93 MKS Cluster V1: add minor version upgrade support
  go.mod
  go.sum
  selectel/mks.go
  selectel/mks_test.go
  vendor/github.com/selectel/mks-go/pkg/v1/client.go
  vendor/github.com/selectel/mks-go/pkg/v1/cluster/doc.go
  vendor/github.com/selectel/mks-go/pkg/v1/cluster/requests.go
  vendor/github.com/selectel/mks-go/pkg/v1/cluster/schemas.go
  vendor/modules.txt
  website/docs/r/mks_cluster_v1.html.markdown
Labels: dependencies, documentation, size/XL

#95 MKS V1: increase default timeouts
  selectel/resource_selectel_mks_cluster_v1.go
  selectel/resource_selectel_mks_nodegroup_v1.go
Labels: size/XS

#96 Upgrade Terraform SDK
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform-plugin-sdk/acctest/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/hashcode/hashcode.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/mutexkv/mutexkv.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_config.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/set.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/httpclient/useragent.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/terraform/state.go
  vendor/modules.txt
Labels: dependencies, size/L

#98 Do retries on 5xx codes from Domains API
  .golangci.yml
  go.mod
  go.sum
  selectel/config.go
  selectel/domains.go
  vendor/github.com/hashicorp/go-retryablehttp/.gitignore
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: dependencies, size/XXL
