Repository selectel/terraform-provider-selectel, pull requests merged in 2024-05, with the labels that each got.

#275 Documentation updates: descriptions for local_volume and volume_type
  website/docs/r/mks_nodegroup_v1.html.markdown
Labels: documentation

#272 Fix project_id tab
  website/docs/r/iam_s3_credentials_v1.html.markdown
  website/docs/r/iam_serviceuser_v1.html.markdown
  website/docs/r/iam_user_v1.html.markdown
Labels: documentation

#260 Use default value for the dbaas lc_* database fields
  selectel/schema_selectel_dbaas_postgresql_database_v1.go
Labels: enhancement, size/S

#276 Fix postgresql database resource field name
  selectel/schema_selectel_dbaas_postgresql_database_v1.go
Labels: size/S

#279 Documentation updates: fixed links, project terms, and navigation in panel
  website/docs/d/dbaas_available_extension_v1.html.markdown
  website/docs/d/dbaas_configuration_parameter_v1.html.markdown
  website/docs/d/dbaas_datastore_type_v1.html.markdown
  website/docs/d/dbaas_flavor_v1.html.markdown
  website/docs/d/dbaas_prometheus_metric_token_v1.html.markdown
  website/docs/d/domains_domain_v1.html.markdown
  website/docs/d/domains_rrset_v2.html.markdown
  website/docs/d/domains_zone_v2.html.markdown
  website/docs/d/mks_admission_controllers_v1.html.markdown
  website/docs/d/mks_feature_gates_v1.html.markdown
  website/docs/d/mks_kube_versions_v1.html.markdown
  website/docs/d/mks_kubeconfig_v1.html.markdown
  website/docs/guides/upgrading_to_version_4.html.markdown
  website/docs/guides/upgrading_to_version_5.html.markdown
  website/docs/index.html.markdown
  website/docs/r/craas_registry_v1.html.markdown
  website/docs/r/craas_token_v1.html.markdown
  website/docs/r/dbaas_grant_v1.html.markdown
  website/docs/r/dbaas_kafka_acl_v1.html.markdown
  website/docs/r/dbaas_kafka_datastore_v1.html.markdown
  website/docs/r/dbaas_kafka_topic_v1.html.markdown
  website/docs/r/dbaas_mysql_database_v1.html.markdown
  website/docs/r/dbaas_mysql_datastore_v1.html.markdown
  website/docs/r/dbaas_postgresql_database_v1.html.markdown
  website/docs/r/dbaas_postgresql_datastore_v1.html.markdown
  website/docs/r/dbaas_postgresql_extension_v1.html.markdown
  website/docs/r/dbaas_postgresql_logical_replication_slot_v1.html.markdown
  website/docs/r/dbaas_prometheus_metric_token_v1.html.markdown
  website/docs/r/dbaas_redis_datastore_v1.html.markdown
  website/docs/r/dbaas_user_v1.html.markdown
  website/docs/r/domains_domain_v1.html.markdown
  website/docs/r/domains_record_v1.html.markdown
  website/docs/r/domains_rrset_v2.html.markdown
  website/docs/r/domains_zone_v2.html.markdown
  website/docs/r/iam_s3_credentials_v1.html.markdown
  website/docs/r/iam_serviceuser_v1.html.markdown
  website/docs/r/iam_user_v1.html.markdown
  website/docs/r/mks_cluster_v1.html.markdown
  website/docs/r/mks_nodegroup_v1.html.markdown
  website/docs/r/secretsmanager_certificate_v1.html.markdown
  website/docs/r/secretsmanager_secret_v1.html.markdown
  website/docs/r/vpc_floatingip_v2.html.markdown
  website/docs/r/vpc_keypair_v2.html.markdown
  website/docs/r/vpc_license_v2.html.markdown
  website/docs/r/vpc_project_v2.html.markdown
  website/docs/r/vpc_role_v2.html.markdown
  website/docs/r/vpc_subnet_v2.html.markdown
  website/docs/r/vpc_token_v2.html.markdown
  website/docs/r/vpc_user_v2.html.markdown
Labels: documentation
