Repository selectel/terraform-provider-selectel, pull requests merged in 2024-08, with the labels that each got.

#285 Add GPU without drivers and nvidia device plugin support to MKS
  go.mod
  go.sum
  selectel/resource_selectel_mks_nodegroup_v1.go
  selectel/resource_selectel_mks_nodegroup_v1_test.go
  website/docs/r/mks_nodegroup_v1.html.markdown
Labels: documentation, size/M

#289 update release.yml workflow
  .github/workflows/release.yml
Labels: bug, size/S

#292 update iam_serviceuser_v1
  website/docs/r/iam_serviceuser_v1.html.markdown
Labels: documentation

#278 Add selectel_dbaas_firewall_v1 resource
  selectel/dbaas.go
  selectel/dbaas_base_schemas.go
  selectel/provider.go
  selectel/resource_selectel_dbaas_firewall_v1.go
  selectel/resource_selectel_dbaas_firewall_v1_test.go
  selectel/schemas/dbaas/schema_selectel_dbaas_firewall_v1.go
  website/docs/r/dbaas_datastore_v1.html.markdown
  website/docs/r/dbaas_firewall_v1.html.markdown
  website/docs/r/dbaas_kafka_datastore_v1.html.markdown
  website/docs/r/dbaas_mysql_datastore_v1.html.markdown
  website/docs/r/dbaas_postgresql_datastore_v1.html.markdown
  website/docs/r/dbaas_redis_datastore_v1.html.markdown
Labels: documentation, new-resource, size/M

#295 Update MKS resources documentation
  website/docs/r/mks_cluster_v1.html.markdown
  website/docs/r/mks_nodegroup_v1.html.markdown
Labels: size/XS, documentation
